stages:
  - setup
  - portal-setup
  - test-setup
  - cypress-test
  - portal-cleanup
  - cleanup

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - CypressE2E/node_modules
    - external_ip.txt

Cluster Connect:
  stage: setup
  tags:
    - litmus-portal
  script:
    - chmod 755 ./build/gitlab/stages/1-gke-setup/cluster-setup
    - ./build/gitlab/stages/1-gke-setup/cluster-setup
  artifacts:
    when: always
    paths:
      - .kube/

Portal-Setup:
  when: always
  stage: portal-setup
  tags: 
    - litmus-portal
  script:
    - chmod 755 ./install.sh
    - ./install.sh
  artifacts:
    when: always
    paths:
      - .kube/

Cypress-Setup:
  when: always
  stage: test-setup
  image: cypress/base:10
  tags:
    - litmus-portal-docker
  script:
    - cd CypressE2E && npm ci
  artifacts:
    when: always
    paths:
      - CypressE2E/node_modules/

Cypress-e2e:
  when: always
  stage: cypress-test
  tags:
    - litmus-portal-docker
  script:
    - cat <<< "external_ip.txt" > "$FRONTEND_IP"
    - echo "$FRONTEND_IP"
    # - cd CypressE2E
    # - npm test
  artifacts:
    when: always
    paths:
      - CypressE2E/cypress/screenshots
      - CypressE2E/cypress/videos

portal-cleanup:
  when: always
  stage: portal-cleanup
  tags: 
    - litmus-portal
  script:
    - kubectl delete -f https://raw.githubusercontent.com/litmuschaos/litmus/master/litmus-portal/k8s-manifest.yml
  artifacts:
    when: always
    paths:
      - .kube/
    
Cluster Disconnect:
  when: always
  stage: cleanup
  tags:
    - litmus-portal
  script: 
    - chmod 755 ./build/gitlab/stages/2-gke-cleanup/cluster-cleanup
    - ./build/gitlab/stages/2-gke-cleanup/cluster-cleanup
  artifacts:
    when: always
    paths:
      - .kube/
