stages:
  # - setup
  # - portal-setup
  # - test-setup
  # - cypress-test
  # - portal-cleanup
  # - cleanup
  - build
  - test

# variables:
#   npm_config_cache: "$CI_PROJECT_DIR/.npm"
#   CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - .npm
#     - cache/Cypress
#     - CypressE2E/node_modules

build:
  stage: build
  script:
    - BUILD_VERSION="Hiiiiii"                            
    - echo "BUILD_VERSION=$BUILD_VERSION" >> build.env    
  artifacts:
    reports:
      dotenv: build.env                                 

deploy:
  stage: deploy
  script:
    - echo "Build version is ${BUILD_VERSION}"            
  dependencies:
    - build

  

# Cluster Connect:
#   image: jonsy13/runner:latest
#   stage: setup
#   tags:
#     - litmus-portal-2
#   script:
#     - chmod 755 ./build/gitlab/stages/1-gke-setup/cluster-setup
#     - ./build/gitlab/stages/1-gke-setup/cluster-setup
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#   cache: {}

# Portal-Setup:
#   image: jonsy13/runner:latest
#   when: always
#   stage: portal-setup
#   tags: 
#     - litmus-portal-2
#   script:
#     - chmod 755 ./install.sh
#     - ./install.sh
#     - echo $FRONTEND_IP
#     - echo "ip=$FRONTEND_IP" >> Portal-Setup.env
#     - echo "$ip"
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#     reports:
#       dotenv: Portal-Setup.env
#   cache: {}

# Cypress-Setup:
#   when: always
#   stage: test-setup
#   image: cypress/base:10
#   tags:
#     - litmus-portal-2
#   script:
#     - cd CypressE2E && npm ci

# Cypress-e2e:
#   when: always
#   stage: cypress-test
#   image: cypress/base:10
#   tags:
#     - litmus-portal-2
#   script:
#     - echo "$ip"
#     - cd CypressE2E
#     - CYPRESS_BASE_URL=http://($ip):9091/ npm test
#   artifacts:
#     when: always
#     paths:
#       - CypressE2E/cypress/screenshots
#       - CypressE2E/cypress/videos
#   dependencies:
#     - Portal-Setup

# portal-cleanup:
#   when: always
#   image: jonsy13/runner:latest
#   stage: portal-cleanup
#   tags: 
#     - litmus-portal-2
#   script:
#     - chmod 755 ./uninstall.sh
#     - ./uninstall.sh
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#   cache: {}
    
# Cluster Disconnect:
#   when: always
#   image: jonsy13/runner:latest
#   stage: cleanup
#   tags:
#     - litmus-portal-2
#   script: 
#     - chmod 755 ./build/gitlab/stages/2-gke-cleanup/cluster-cleanup
#     - ./build/gitlab/stages/2-gke-cleanup/cluster-cleanup
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#   cache: {}
