stages:
  - setup
#   - test-setup 
#   - clean-setup
  - cleanup

cache:
  key: ${CI_COMMIT_REF_SLUG}

Cluster Connect:
  stage: setup
  tags:
    - litmus-portal
  script:
    - chmod +x ./install.sh
    - sudo ./install.sh
  artifacts:
    when: always
    paths:
      - .kube/

Cluster Disconnect:
  stage: cleanup
  tags:
    - litmus-portal
  script:
    - chmod +x ./uninstall.sh
    - sudo ./uninstall.sh
  artifacts:
    when: always
    paths:
      - .kube/



