stages:
  - setup
  - portal-setup
  - test-setup
  - pre-test-setup
  - cypress-test
  - portal-cleanup
  - cleanup

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - CypressE2E/node_modules

Cluster Connect:
  image: jonsy13/runner:latest
  stage: setup
  tags:
    - litmus-portal-2
  script:
    - chmod 755 ./build/gitlab/stages/1-gke-setup/cluster-setup
    - ./build/gitlab/stages/1-gke-setup/cluster-setup
  artifacts:
    when: always
    paths:
      - .kube/
  cache: {}

Portal-Setup:
  image: jonsy13/runner:latest
  when: always
  stage: portal-setup
  tags: 
    - litmus-portal-2
  script:
    - chmod 755 ./install.sh
    - ./install.sh
  artifacts:
    when: always
    paths:
      - .kube/
    reports:
      dotenv: Portal-Setup.env
  cache: {}

Cypress-Setup:
  when: always
  stage: test-setup
  image: cypress/base:10
  tags:
    - litmus-portal-2
  script:
    - cd CypressE2E && npm ci

PreTest-Setup:
  when: always
  stage: pre-test-setup
  image: cypress/base:10
  tags:
    - litmus-portal-2
  script:
    - cd CypressE2E
    - CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ npm run Basic_Setup
  artifacts:
    when: always
    paths:
      - CypressE2E/cypress/screenshots
  dependencies:
    - Portal-Setup

.cypress-e2e:
  when: always
  stage: cypress-test
  image: cypress/base:10
  tags:
    - litmus-portal-2
  script:
    - echo ${FRONTEND_IP}
  artifacts:
    when: always
    paths:
      - CypressE2E/cypress/screenshots
  dependencies:
    - Portal-Setup

routes-check:
  extends: .cypress-e2e
  script:
    - cd CypressE2E && CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ npm run Parallel_Tests --config testFiles='Parallel_Tests/Routes/*.spec.js'

create-workflow:
  extends: .cypress-e2e
  script: 
    - cd CypressE2E && CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ npm run Parallel_Tests --config testFiles='Parallel_Tests/Create_Workflow/*.spec.js'

community-data:
  extends: .cypress-e2e
  script: 
    - cd CypressE2E && CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ npm run Parallel_Tests --config testFiles='Parallel_Tests/Community/*.spec.js'

portal-cleanup:
  when: always
  image: jonsy13/runner:latest
  stage: portal-cleanup
  tags: 
    - litmus-portal-2
  script:
    - chmod 755 ./uninstall.sh
    - ./uninstall.sh
  artifacts:
    when: always
    paths:
      - .kube/
  cache: {}
    
Cluster Disconnect:
  when: always
  image: jonsy13/runner:latest
  stage: cleanup
  tags:
    - litmus-portal-2
  script: 
    - chmod 755 ./build/gitlab/stages/2-gke-cleanup/cluster-cleanup
    - ./build/gitlab/stages/2-gke-cleanup/cluster-cleanup
  artifacts:
    when: always
    paths:
      - .kube/
  cache: {}
