---
stages:
  - setup
  # - cypress-test
  - cleanup


# variables:
#   npm_config_cache: "$CI_PROJECT_DIR/CypressE2E/.npm"
#   CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/CypressE2E/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  # paths:
  #   - CypressE2E/.npm
  #   - CypressE2E/cache/Cypress
  #   - CypressE2E/node_modules

Cluster Connect:
  stage: setup
  tags:
    - litmus-portal
  script:
    - chmod 755 ./build/gitlab/stages/1-gke-setup/cluster-setup
    - ./build/gitlab/stages/1-gke-setup/cluster-setup
  artifacts:
    when: always
    paths:
      - .kube/

# Cypress-e2e:
#   when: always
#   image: cypress/browsers:latest
#   stage: cypress-test
#   tags:
#     - litmus-portal
#   script:
#     - cd CypressE2E && npm ci
#     - cd ../ && git clone -b litmus-portal https://github.com/litmuschaos/litmus.git
#     - cd litmus/litmus-portal/frontend && npm ci
#     - CHOKIDAR_USEPOLLING=1 npm start &
#     - cd ../../../CypressE2E
#     - npm test
#   artifacts:
#     when: always
#     paths:
#       - CypressE2E/cypress/screenshots
#       - CypressE2E/cypress/videos
#       - .kube/

Cluster Disconnect:
  when: always
  stage: cleanup
  tags:
    - litmus-portal
  script: 
    - chmod 755 ./build/gitlab/stages/2-gke-setup/cluster-cleanup
    - ./build/gitlab/stages/2-gke-setup/cluster-cleanup
  artifacts:
    when: always
    paths:
      - .kube/

